language: python
python:
  - "3.6"

services:
  - docker


script:
  - docker build -t src

notifications:
  email:
    recipients:
      - blue_tie@hotmail.com
    on_success: never
    on_failure: never